### ISSUE TITLE
Umstellen der PrimaryKeys (ids) auf UUID

### ISSUE THREAD

**Issue by Dehfw** [JacobGsell/superschlag-service#1]
aktuell sind alle ids vom Typ Long. das macht die ids erratbar und stellt ein potentielles Sicherheitsrisiko dar. Ist auch irgendwo in den OWASP drin.

Eine Umstellung auf UUIDs würde Abhilfe schaffen

**Comment by Dehfw** [comment]
https://cheatsheetseries.owasp.org/cheatsheets/Insecure_Direct_Object_Reference_Prevention_Cheat_Sheet.html

**Comment by JacobGsell** [comment]
Done! Commit: https://github.com/JacobGsell/superschlag-service/commit/aa07611191c1eb20f0e0e5d1362f082152935f50
